server:
  port: 8080
  servlet:
    context-path: /diancan
spring:
  datasource:
    url: jdbc:mysql://localhost/diancan?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

